main: plugin.thirdlife.Main
name: ThirdLife
version: 1.5.0
api-version: 1.19
author: HMSValorous
description: Plugin based on the YT series ThirdLife/LastLife

commands:
  thirdlife:
    description: General command interface for ThirdLife
    aliases: tl

permissions:
  thirdlife.admin:
    description: ThirdLife operator
    default: op
  thirdlife.use:
    description: Utilise ThirdLife system
    default: true